# Generated by Django 4.0.4 on 2023-05-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trained', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_panel',
        ),
        migrations.RemoveField(
            model_name='menuss',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.DeleteModel(
            name='user_panel',
        ),
        migrations.DeleteModel(
            name='Menuss',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
