# Generated by Django 4.0.4 on 2023-05-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='question1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
