# Generated by Django 4.0.4 on 2023-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained', '0002_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
