# Generated by Django 4.0.4 on 2023-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained', '0003_submenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='answer1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submenu',
            name='answer1',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
