# Generated by Django 4.0.4 on 2023-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=100)),
                ('column2', models.IntegerField()),
                ('column3', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'my_table_name',
                'managed': False,
            },
        ),
    ]
